ENH: Clean up lesson
Clean up lesson:
- Remove contents in `_episodes_md` folder: the lesson contents being
  pulled at the Carpentries website are hosted in the `_episodes`
  folder.
- Update the episode content table in the `README` file: add missing
  episodes, and update schedule and questions.

This cleanup is necessary for the transition to the new Carpentries
Workbench infrastructure. Avoids the error:
```
Error: cannot open the connection
✖ There were issues with the lesson build process, see 'carpentries-incubator/SDC-BIDS-IntroMRI.err for details'
Warning messages:
1: In file(con, "r") :
  'raw = FALSE' but '/home/jhlegarreta/src/carp-transit-intromri/release/carpentries-incubator/SDC-BIDS-IntroMRI/_episodes_md' is not a regular file
2: In file(con, "r") :
  cannot open file '/home/jhlegarreta/src/carp-transit-intromri/release/carpentries-incubator/SDC-BIDS-IntroMRI/_episodes_md': it is a directory
```

at the
```
make release/carpentries-incubator/SDC-BIDS-IntroMRI.json
```

step.

See
https://carpentries.github.io/sandpaper-docs/migrating-from-styles.html
for the transition steps.